export default [
  'PatientName',
  'PatientID',
  'PatientBirthDate',
  'PatientAge',
  'PatientSex',
  'AccessionNumber',
  'StationName',
  'StudyDescription',
  'Modality',
  'StudyDate',
  'StudyInstanceUID',
  'ReferringPhysicianName',
  'ScheduledStudyLocationAETitle',
];
